name: env_batch_{{cookiecutter.model_class}}
channels:
  - defaults
  - conda-forge
  - pip
dependencies:
  - python>=3.8
  - click=7.1.1
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.7.1
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.4=py_0
  - keyring>=23
  - matplotlib>=3.3.4
  - pandas>=1.0.3
  - pyodbc>=4.0.30
  - shap>=0.39
  - spyder>=5
  - spyder-kernels>=2
  - sqlalchemy=1.3.17=py37he774522_0
  - xgboost>=1.42